apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stk111-stk111-poi-map-app-dev
  annotations:
    argocd/app-name: stk111-stk111-poi-map-app-dev
    backstage.io/kubernetes-id: stk111-stk111-poi-map-app-dev
    backstage.io/kubernetes-namespace: stk111
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=stk111-stk111-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/stk111-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/stk111/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/stk111/deployments/stk111-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/stk111-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://stk111-poi-map-app-stk111.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/stk111"
  system: workshop-system-stk111
  consumesApis:
    - gateway-api-stk111
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-stk111
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/stk111"
